apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: nginx-vishnu
    image: nginx
    ports:
    - containerPort: 8080
  - name: watcher-vishnu
    image: afakharany/watcher
    ports:
    - containerPort: 8081
