apiVersion: v1
kind: Service
metadata:
  name: python-helloworld-service
spec:
  ports:
    - port: 31003
      nodePort: 31004
      targetPort: python-port
      protocol: TCP
  selector:
    app: python-helloworld
  type: NodePort
